2020-04-03 17:21:03,511 [INFO] databases.crmsdb: Database connected
2020-04-03 17:21:03,511 [INFO] databases.crmsdb: Bắt đầu - lấy thông tin các bảng params HSDN
2020-04-03 17:21:05,384 [INFO] databases.crmsdb: kết thúc - lấy thông tin các bảng params HSDN
2020-04-03 17:21:05,384 [INFO] databases.crmsdb: Bắt đầu - lấy thông tin QLT_THONGTINDOANHNGHIEP
2020-04-03 17:21:07,905 [INFO] databases.crmsdb: kết thúc - lấy thông tin QLT_THONGTINDOANHNGHIEP
2020-04-03 17:21:07,907 [INFO] datamodels.crms.qlt_hsvp_xhdn: ------Bắt đầu đánh giá RANK HSDN ---------
2020-04-03 17:21:11,551 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0100365533 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:11,552 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0100365533 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:11,552 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0100365533 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:11,553 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0100365533 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:11,712 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0100893501 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:11,713 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0100893501 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:11,713 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0100893501 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:11,713 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0100893501 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:12,124 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0101742512 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:12,125 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0101742512 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:12,125 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0101742512 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:12,125 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0101742512 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:18,476 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0201723739 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:18,477 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0201723739 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:18,477 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0201723739 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:18,478 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0201723739 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:18,677 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0201838024 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:18,678 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0201838024 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:18,678 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0201838024 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:18,678 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0201838024 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:23,268 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0305647666 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:23,268 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0305647666 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:23,269 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0305647666 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:23,269 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0305647666 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:23,692 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0309561868 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:23,692 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0309561868 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:23,693 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0309561868 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:23,693 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0309561868 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:28,084 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0401502938 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:28,086 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0401502938 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:28,086 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0401502938 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:28,087 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0401502938 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:31,785 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 2301018082 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:31,786 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 2301018082 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:31,786 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 2301018082 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:31,787 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 2301018082 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:33,233 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0311083922 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:33,233 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0311083922 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:33,234 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0311083922 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:33,234 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0311083922 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:33,370 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0311178998 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:33,370 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0311178998 Lỗi Giá trị None ID_TIEUCHI : 160101
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:33,371 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0311178998 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:33,371 [ERROR] datamodels.crms.qlt_hsdn_xhdn: MA_DN : 0311178998 Lỗi Giá trị None ID_TIEUCHI : 160102
Traceback (most recent call last):
  File "E:\10.Python\git_svn\khoailangtotet\services\process_hsdn_rank.py", line 67, in set_diem_tieuchi_hsdn
    if kl.GIA_TRI <= item.GIATRI:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2020-04-03 17:21:37,099 [INFO] datamodels.crms.qlt_hsvp_xhdn: ------Kết thúc đánh giá RANK HSDN ---------
2020-04-03 17:21:37,100 [INFO] databases.crmsdb: Bắt đầu - lấy thông tin các bảng params HSVP
2020-04-03 17:21:41,510 [INFO] databases.crmsdb: kết thúc - lấy thông tin các bảng params HSVP
2020-04-03 17:21:41,511 [INFO] databases.crmsdb: Bắt đầu - lấy thông tin QLT_THONGTINVIPHAM
2020-04-03 17:21:48,133 [INFO] databases.crmsdb: kết thúc - lấy thông tin QLT_THONGTINVIPHAM
2020-04-03 17:21:48,136 [INFO] datamodels.crms.qlt_hsvp_xhdn: ------Bắt đầu đánh giá RANK HSVP ---------
2020-04-03 17:23:50,707 [INFO] datamodels.crms.qlt_hsvp_xhdn: ------Kết thúc đánh giá RANK HSVP ---------
2020-04-03 17:23:50,707 [INFO] datamodels.crms.qlt_hsvp_xhdn: ------Kết thúc đánh giá RANK ---------
2020-04-03 17:28:18,933 [INFO] databases.crmsdb: Database connected
2020-04-03 17:28:18,934 [INFO] databases.crmsdb: Bắt đầu - lấy thông tin các bảng params HSDN
2020-04-03 17:28:20,065 [INFO] databases.crmsdb: kết thúc - lấy thông tin các bảng params HSDN
2020-04-03 17:28:20,065 [INFO] databases.crmsdb: Bắt đầu - lấy thông tin QLT_THONGTINDOANHNGHIEP
2020-04-03 17:28:22,805 [INFO] databases.crmsdb: kết thúc - lấy thông tin QLT_THONGTINDOANHNGHIEP
2020-04-03 17:28:22,809 [INFO] datamodels.crms.qlt_hsvp_xhdn: ------Bắt đầu đánh giá RANK HSDN ---------
2020-04-03 17:28:54,375 [INFO] datamodels.crms.qlt_hsvp_xhdn: ------Kết thúc đánh giá RANK HSDN ---------
2020-04-03 17:28:54,375 [INFO] databases.crmsdb: Bắt đầu - lấy thông tin các bảng params HSVP
2020-04-03 17:28:58,575 [INFO] databases.crmsdb: kết thúc - lấy thông tin các bảng params HSVP
2020-04-03 17:28:58,576 [INFO] databases.crmsdb: Bắt đầu - lấy thông tin QLT_THONGTINVIPHAM
2020-04-03 17:29:05,681 [INFO] databases.crmsdb: kết thúc - lấy thông tin QLT_THONGTINVIPHAM
2020-04-03 17:29:05,684 [INFO] datamodels.crms.qlt_hsvp_xhdn: ------Bắt đầu đánh giá RANK HSVP ---------
2020-04-03 17:31:09,718 [INFO] datamodels.crms.qlt_hsvp_xhdn: ------Kết thúc đánh giá RANK HSVP ---------
2020-04-03 17:31:09,718 [INFO] datamodels.crms.qlt_hsvp_xhdn: ------Kết thúc đánh giá RANK ---------
